title: Sandro's Notes
description: Welcome to my personal notes on Machine Learning.
baseurl: "/notes"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
    - jekyll/scholar
